#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

title: Jupyter Book Blog Template
author: Blog Author
copyright: ''
logo: images/general/logo.png
exclude_patterns:
- _build
- Thumbs.db
- .DS_Store
- '**.ipynb_checkpoints'
only_build_toc_files: true
execute:
  execute_notebooks: auto
  cache: ''
  exclude_patterns: []
  timeout: 100
  run_in_temp: false
  allow_errors: false
  stderr_output: show
launch_buttons:
  colab_url: https://colab.research.google.com
  notebook_interface: jupyterlab
  binderhub_url: https://mybinder.org
repository:
  url: https://github.com/yourusername/jupyter-book-blog
  branch: main
html:
  favicon: images/general/logo.png
  baseurl: https://yourusername.github.io/jupyter-book-blog
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  use_download_button: true
  extra_css:
  - _static/mermaid.css
sphinx:
  config:
    html_js_files:
    - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
    - _static/mermaid-init.js
    html_theme_options:
      use_download_button: true
      repository_url: https://github.com/yourusername/jupyter-book-blog
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
      launch_buttons:
        binderhub_url: https://mybinder.org
        colab_url: https://colab.research.google.com
      extra_footer: '<p>

        © 2024 Blog Author. All rights reserved.

        </p>'
    myst_enable_extensions:
    - html_image
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
    bibtex_reference_style: author_year
bibtex_bibfiles:
- references/global.bib
